# Generated by Django 3.2.7 on 2021-10-08 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.CharField(choices=[('Mechanical', 'Mechanical'), ('Civil ', 'Civil '), ('Electrical', 'Electrical'), ('ComputerScience', 'Computer Science'), ('Electronics&Communication', 'Electronics & Communication'), ('placement', 'Placement'), ('admission', 'Admission'), ('event', 'Event'), ('CDC', 'CDC')], default='Computer Science', max_length=40),
        ),
    ]
